### ISSUE TITLE
Template Validation Error - "Microsoft.Network/networksecuritygroups/nsg-rdp-allow"

### ISSUE THREAD

**Issue by T0pCyber** [Azure/SimuLand#11]
When attempting to deploy simuland, and completing all the required fields, we keep on getting "Template Validation Error". This seems to be an error from the downstream Win10-AD-ADFS template. Our desired configuration is to use AzureBastion. We selected AzureBastionHost and left the "Allowed IP Addresses" blank. Can't seem to figure out how to fix this in our deployment. Thanks.

![image](https://user-images.githubusercontent.com/10575720/123112106-75bd4880-d40b-11eb-9aa4-b463424eb4fd.png)

![image](https://user-images.githubusercontent.com/10575720/123111293-cc765280-d40a-11eb-873c-bef0cb8f2405.png)

**Comment by Cyb3rWard0g** [comment]
Hello @T0pCyber !

Would you mind keeping the AllowedIP Address as `*`? It is set by default but it is not used since AzureBastionHost is the defaut. I see you are using the `Deploy to Azure` blue button in the README of the deploy document right? The following one: https://github.com/Azure/SimuLand/tree/main/2_deploy/aadHybridIdentityADFS#azure-ad-hybrid-identity-active-directory-federation-services-ad-fs-deployment

**Comment by Cyb3rWard0g** [comment]
I deployed it via the Azure CLI following the docs and it worked just fine. I have not tested the ARM template via the 'Deploy to Azure' blue button

![image](https://user-images.githubusercontent.com/9653181/123198170-a2f50f80-d47a-11eb-9c31-c9e6fcd2f9cf.png)

**Comment by T0pCyber** [comment]
Is there a dependency on the Domain name? Do I need to use Simuland.com?

**Comment by T0pCyber** [comment]
I was able to get it deployed using the Azure CLI  steps. Had some errors but I think I know why that happened. My assumption is that the Deploy to Azure link would work.

**Comment by Cyb3rWard0g** [comment]
Hello @T0pCyber ! Yes I added the domain name to the Azure CLI example in the docs.
