### ISSUE TITLE
Cost Analysis Question

### ISSUE THREAD

**Issue by Dabuek** [Azure/SimuLand#27]
Hi,

I was wondering whether there is any optimum way to deploy this solution? Right now my predicted costs on this subscription seem to be sky rocketing.

![image](https://user-images.githubusercontent.com/13871600/157642688-392646aa-bc93-4e4e-bb04-f9b14df329de.png)

Cheers

**Comment by Cyb3rWard0g** [comment]
Hello Dabuek!

I believe one of the expensive services is the Bastion Host. For security purposes and to integrate it with access to your portal and resource group, it is a good to have. However, it can be expensive. Therefore, the template also has the options to simply use a NSG rule to only allow access from a public IP address. Set the following parameter to `AllowPublicIP`.

https://github.com/Azure/SimuLand/blob/main/2_deploy/aadHybridIdentityADFS/azuredeploy.json#L112

Make sure you set the specific IP address in this parameter (it is set to `*` by default):

https://github.com/Azure/SimuLand/blob/main/2_deploy/aadHybridIdentityADFS/azuredeploy.json#L123

That should help a lot! Also, from a MS Sentinel perspective, you can adjust the XPath queries used to collect data from Windows Security events and other Win providers (i.e. Sysmon). You can adjust the queries before deployment via the template parameters:
* Windows Security Auditing provider: https://github.com/Azure/SimuLand/blob/main/2_deploy/aadHybridIdentityADFS/azuredeploy.json#L190
* https://github.com/Azure/SimuLand/blob/main/2_deploy/aadHybridIdentityADFS/azuredeploy.json#L221

or via Microsoft Sentinel data connectors UI:

![image](https://user-images.githubusercontent.com/9653181/157660209-95167472-812a-4f04-8cc3-fb9230f5c9ad.png)

Also since this is a lab environment, I would set a policy to shutdown at least the domain-joined workstations.

I hope this helps!
